import { zodResolver } from '@hookform/resolvers/zod';
import { AnimatePresence, motion } from 'framer-motion';
import { useState } from 'react';
import { Controller, useForm } from 'react-hook-form';
import toast from 'react-hot-toast';
import { FiEye, FiSave, FiSend, FiX } from 'react-icons/fi';
import { useNavigate } from 'react-router-dom';

import { JobPreviewContent } from '@/components/CompanyJobs/JobPreviewContent';
import { RichTextEditor } from '@/components/CompanyJobs/RichTextEditor';
import { companyService } from '@/services/companyService';
import type { CompanyJob, CompanyJobStatus } from '@/types/company';
import { formValuesToJob, jobToFormValues } from '@/utils/companyJobs';
import { companyJobSchema, type CompanyJobFormValues } from '@/validation/companyJobSchema';

const defaults: CompanyJobFormValues = { title: '', company: 'Northstar Labs', department: '', description: '', responsibilities: '', skills: '', preferred_skills: '', experience_level: 'Mid-level', salary_range: '', employment_type: 'Full-time', work_mode: 'Hybrid', location: '', openings: 1, category: 'Engineering', tags: '', application_deadline: '', benefits: '', education: '', requirements: '' };
const input = 'mt-2 h-11 w-full rounded-lg border border-slate-300 bg-white px-3 text-sm outline-none focus:border-cyan-500 dark:border-white/15 dark:bg-white/5';
const area = 'mt-2 min-h-28 w-full rounded-lg border border-slate-300 bg-white p-3 text-sm leading-6 outline-none focus:border-cyan-500 dark:border-white/15 dark:bg-white/5';

export function CompanyJobForm({ initialJob, jobId }: { initialJob?: CompanyJob; jobId?: string }) {
  const navigate = useNavigate();
  const { control, getValues, handleSubmit, register, formState: { errors, isSubmitting } } = useForm<CompanyJobFormValues>({ resolver: zodResolver(companyJobSchema), defaultValues: initialJob ? jobToFormValues(initialJob) : defaults });
  const [previewOpen, setPreviewOpen] = useState(false);
  async function save(values: CompanyJobFormValues, status: CompanyJobStatus) { const payload = formValuesToJob(values, status); if (jobId) await companyService.updateJob(jobId, payload); else await companyService.createJob(payload); toast.success(status === 'published' ? 'Job published successfully.' : 'Job saved as draft.'); navigate('/company/dashboard/jobs'); }
  const previewJob = formValuesToJob(getValues(), initialJob?.status ?? 'draft');
  return <><form className="space-y-6" onSubmit={handleSubmit((values) => save(values, 'published'))}>
    <FormSection title="Role basics"><div className="grid gap-5 md:grid-cols-2"><Field error={errors.title?.message} label="Job Title"><input className={input} {...register('title')} /></Field><Field error={errors.company?.message} label="Company"><input className={input} {...register('company')} /></Field><Field error={errors.department?.message} label="Department"><input className={input} {...register('department')} /></Field><Field error={errors.category?.message} label="Category"><select className={input} {...register('category')}><option>Engineering</option><option>Design</option><option>Product</option><option>Data</option><option>Sales</option><option>Operations</option></select></Field><Field label="Employment Type"><select className={input} {...register('employment_type')}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Internship</option></select></Field><Field label="Experience"><select className={input} {...register('experience_level')}><option>Entry-level</option><option>Mid-level</option><option>Senior</option><option>Lead</option><option>Executive</option></select></Field><Field error={errors.salary_range?.message} label="Salary Range"><input className={input} placeholder="$120k-$160k" {...register('salary_range')} /></Field><Field label="Work Mode"><select className={input} {...register('work_mode')}><option>Remote</option><option>Hybrid</option><option>Onsite</option></select></Field><Field error={errors.location?.message} label="Location"><input className={input} {...register('location')} /></Field><Field error={errors.openings?.message} label="Openings"><input className={input} type="number" {...register('openings', { valueAsNumber: true })} /></Field><Field error={errors.application_deadline?.message} label="Deadline"><input className={input} type="date" {...register('application_deadline')} /></Field><Field error={errors.education?.message} label="Education"><input className={input} {...register('education')} /></Field></div></FormSection>
    <FormSection title="Job description"><Field error={errors.description?.message} label="Description"><Controller control={control} name="description" render={({ field }) => <RichTextEditor onChange={field.onChange} value={field.value} />} /></Field><div className="mt-5 grid gap-5 lg:grid-cols-2"><Field error={errors.responsibilities?.message} label="Responsibilities"><textarea className={area} placeholder="One item per line" {...register('responsibilities')} /></Field><Field error={errors.requirements?.message} label="Requirements"><textarea className={area} placeholder="One item per line" {...register('requirements')} /></Field></div></FormSection>
    <FormSection title="Skills and benefits"><div className="grid gap-5 md:grid-cols-2"><Field error={errors.skills?.message} label="Required Skills"><input className={input} placeholder="React, TypeScript, Testing" {...register('skills')} /></Field><Field label="Preferred Skills"><input className={input} placeholder="Design Systems, Playwright" {...register('preferred_skills')} /></Field><Field label="Tags"><input className={input} placeholder="SaaS, Enterprise, B2B" {...register('tags')} /></Field><Field label="Benefits"><textarea className={area} placeholder="One item per line" {...register('benefits')} /></Field></div></FormSection>
    <div className="flex flex-wrap justify-end gap-3"><button className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2.5 font-bold dark:border-white/15" onClick={() => setPreviewOpen(true)} type="button"><FiEye />Preview</button><button className="inline-flex items-center gap-2 rounded-lg border border-cyan-600 px-4 py-2.5 font-bold text-cyan-700 dark:text-cyan-300" disabled={isSubmitting} onClick={handleSubmit((values) => save(values, 'draft'))} type="button"><FiSave />Save Draft</button><button className="inline-flex items-center gap-2 rounded-lg bg-cyan-600 px-4 py-2.5 font-bold text-white disabled:opacity-50" disabled={isSubmitting} type="submit"><FiSend />{jobId ? 'Save & Publish' : 'Publish Job'}</button></div>
  </form><AnimatePresence>{previewOpen ? <motion.div animate={{ opacity: 1 }} className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/70 p-4 sm:p-8" exit={{ opacity: 0 }} initial={{ opacity: 0 }}><div className="mx-auto max-w-5xl"><div className="mb-3 flex justify-end"><button aria-label="Close preview" className="grid size-10 place-items-center rounded-lg bg-white text-slate-950" onClick={() => setPreviewOpen(false)} type="button"><FiX /></button></div><JobPreviewContent job={previewJob} /></div></motion.div> : null}</AnimatePresence></>;
}
function FormSection({ title, children }: { title: string; children: React.ReactNode }) { return <motion.section animate={{ opacity: 1, y: 0 }} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900/70" initial={{ opacity: 0, y: 12 }}><h2 className="text-lg font-bold">{title}</h2><div className="mt-5">{children}</div></motion.section>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <label className="text-sm font-bold text-slate-700 dark:text-slate-200">{label}{children}{error ? <span className="mt-1 block text-xs text-rose-600">{error}</span> : null}</label>; }
