import { useEffect, useRef, useState } from 'react';
import { FiBell, FiChevronDown, FiChevronLeft, FiChevronRight, FiHome, FiLogOut, FiMenu, FiMoon, FiSearch, FiSettings, FiSun, FiX } from 'react-icons/fi';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { BrandLogo } from '@/components/BrandLogo';
import { ADMIN_NAV_ITEMS } from '@/constants/adminDashboard';
import { useAuth } from '@/hooks/useAuth';
import { useThemeMode } from '@/hooks/useThemeMode';

export function AdminSidebar({ collapsed, open, onClose, onLogout, onToggle }: { collapsed: boolean; open: boolean; onClose: () => void; onLogout: () => void; onToggle: () => void }) {
  const ref = useRef<HTMLElement>(null);
  useEffect(() => { let context: gsap.Context | undefined; void import('gsap').then(({ default: gsap }) => { context = gsap.context(() => gsap.fromTo('.admin-nav-item', { opacity: 0, x: -12 }, { opacity: 1, x: 0, duration: 0.35, stagger: 0.02 }), ref); }); return () => context?.revert(); }, []);
  return <><button aria-label="Close sidebar" className={`fixed inset-0 z-40 bg-slate-950/55 backdrop-blur-sm lg:hidden ${open ? 'opacity-100' : 'pointer-events-none opacity-0'}`} onClick={onClose} type="button" /><aside className={`fixed inset-y-0 left-0 z-50 flex w-72 flex-col border-r border-slate-200 bg-white/95 shadow-2xl backdrop-blur-xl transition-all duration-300 lg:sticky lg:top-0 lg:z-auto lg:h-screen lg:translate-x-0 lg:shadow-none dark:border-white/10 dark:bg-slate-950/95 ${open ? 'translate-x-0' : '-translate-x-full'} ${collapsed ? 'lg:w-20' : 'lg:w-72'}`}><div className="flex h-16 items-center justify-between gap-3 border-b border-slate-200 px-4 dark:border-white/10"><NavLink className="flex items-center gap-3" onClick={onClose} to="/admin/dashboard"><BrandLogo /><span className={`font-bold ${collapsed ? 'lg:sr-only' : ''}`}>AIHire Admin</span></NavLink><button aria-label="Close sidebar" className="lg:hidden" onClick={onClose} type="button"><FiX /></button><button aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} className="hidden size-9 place-items-center rounded-md hover:bg-slate-100 lg:grid dark:hover:bg-white/10" onClick={onToggle} type="button">{collapsed ? <FiChevronRight /> : <FiChevronLeft />}</button></div><nav className="flex-1 space-y-1 overflow-y-auto px-3 py-4" ref={ref}>{ADMIN_NAV_ITEMS.map((item) => { const Icon = item.icon; return <NavLink className={({ isActive }) => `admin-nav-item flex min-h-11 items-center gap-3 rounded-lg px-3 text-sm font-bold transition ${isActive ? 'bg-rose-600 text-white shadow-lg shadow-rose-900/15' : 'text-slate-600 hover:bg-slate-100 hover:text-slate-950 dark:text-slate-300 dark:hover:bg-white/10 dark:hover:text-white'} ${collapsed ? 'lg:justify-center' : ''}`} end={item.end} key={item.id} onClick={onClose} title={collapsed ? item.label : undefined} to={item.to}><Icon className="size-5 shrink-0" /><span className={collapsed ? 'lg:sr-only' : ''}>{item.label}</span></NavLink>; })}</nav><div className="border-t border-slate-200 p-3 dark:border-white/10"><button className={`flex min-h-11 w-full items-center gap-3 rounded-lg px-3 font-bold text-rose-600 hover:bg-rose-50 ${collapsed ? 'lg:justify-center' : ''}`} onClick={onLogout} type="button"><FiLogOut /><span className={collapsed ? 'lg:sr-only' : ''}>Logout</span></button></div></aside></>;
}

export function AdminTopbar({ onLogout, onMenu }: { onLogout: () => void; onMenu: () => void }) {
  const { user } = useAuth(); const { isDark, toggleTheme } = useThemeMode(); const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-30 border-b border-slate-200 bg-slate-50/85 px-4 py-3 backdrop-blur-xl sm:px-6 lg:px-8 dark:border-white/10 dark:bg-slate-950/80"><div className="mx-auto flex max-w-7xl items-center gap-3"><button aria-label="Open sidebar" className="grid size-10 place-items-center rounded-md border bg-white lg:hidden dark:border-white/10 dark:bg-white/10" onClick={onMenu} type="button"><FiMenu /></button><label className="hidden h-11 flex-1 items-center gap-3 rounded-lg border border-slate-200 bg-white px-4 md:flex dark:border-white/10 dark:bg-white/5"><FiSearch className="text-rose-600" /><input className="w-full bg-transparent text-sm outline-none" placeholder="Search users, companies, jobs, logs..." /></label><div className="ml-auto flex items-center gap-2"><Link aria-label="Notifications" className="relative grid size-10 place-items-center rounded-md border bg-white dark:border-white/10 dark:bg-white/10" to="/admin/dashboard/notifications"><FiBell /><span className="absolute right-2 top-2 size-2 rounded-full bg-rose-500" /></Link><button aria-label="Toggle theme" className="grid size-10 place-items-center rounded-md border bg-white dark:border-white/10 dark:bg-white/10" onClick={toggleTheme} type="button">{isDark ? <FiSun /> : <FiMoon />}</button><div className="relative"><button aria-expanded={open} className="flex h-10 items-center gap-2 rounded-lg border bg-white pl-1.5 pr-3 dark:border-white/10 dark:bg-white/10" onClick={() => setOpen((value) => !value)} type="button"><span className="grid size-8 place-items-center rounded-md bg-rose-600 font-bold text-white">{user?.first_name?.[0] ?? 'A'}</span><span className="hidden text-sm font-bold sm:block">{user?.first_name ?? 'Admin'}</span><FiChevronDown /></button>{open ? <div className="absolute right-0 mt-3 w-52 rounded-lg border bg-white p-2 shadow-2xl dark:border-white/10 dark:bg-slate-900"><Link className="flex items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-white/10" to="/admin/dashboard/settings"><FiSettings />Admin Settings</Link><button className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold text-rose-600 hover:bg-rose-50" onClick={onLogout}><FiLogOut />Logout</button></div> : null}</div></div></div><label className="mt-3 flex h-11 items-center gap-3 rounded-lg border bg-white px-3 md:hidden dark:border-white/10 dark:bg-white/5"><FiSearch /><input className="w-full bg-transparent text-sm outline-none" placeholder="Search admin workspace..." /></label></header>;
}

const labels: Record<string, string> = { users: 'User Management', companies: 'Company Management', jobs: 'Job Management', applications: 'Applications', reports: 'Reports', analytics: 'Analytics', notifications: 'Notifications', activity: 'Activity Logs', audit: 'Audit Logs', support: 'Support Tickets', feedback: 'Feedback', 'ai-settings': 'AI Settings', settings: 'System Settings' };
export function AdminBreadcrumbs() { const section = useLocation().pathname.replace('/admin/dashboard', '').split('/').filter(Boolean)[0]; return <nav aria-label="Breadcrumb" className="flex items-center gap-2 text-sm"><Link className="flex items-center gap-2 font-semibold text-slate-500 hover:text-rose-600" to="/admin/dashboard"><FiHome />Dashboard</Link>{section ? <><FiChevronRight className="text-slate-400" /><span className="font-bold">{labels[section] ?? 'Administration'}</span></> : null}</nav>; }
