import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { FiChevronDown, FiDownload, FiSearch } from 'react-icons/fi';
import type { AdminRecord } from '@/types/admin';

export interface AdminColumn { key: string; label: string }
interface Props { data: AdminRecord[]; columns: AdminColumn[]; filterKey?: string; title: string }
const pageSize = 4;

export function AdminTable({ data, columns, filterKey, title }: Props) {
  const [search, setSearch] = useState(''); const [filter, setFilter] = useState('all'); const [sortKey, setSortKey] = useState(columns[0]?.key ?? 'id'); const [ascending, setAscending] = useState(true); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]);
  const options = useMemo(() => filterKey ? [...new Set(data.map((item) => String(item[filterKey])))].sort() : [], [data, filterKey]);
  const filtered = useMemo(() => data.filter((item) => (filter === 'all' || !filterKey || String(item[filterKey]) === filter) && Object.values(item).some((value) => String(value).toLowerCase().includes(search.toLowerCase()))).sort((a, b) => { const left = a[sortKey]; const right = b[sortKey]; return (typeof left === 'number' && typeof right === 'number' ? left - right : String(left).localeCompare(String(right))) * (ascending ? 1 : -1); }), [ascending, data, filter, filterKey, search, sortKey]);
  useEffect(() => setPage(1), [filter, search, sortKey]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const allVisibleSelected = visible.length > 0 && visible.every((item) => selected.includes(item.id));
  function toggleSort(key: string) { if (sortKey === key) setAscending((value) => !value); else { setSortKey(key); setAscending(true); } }
  function togglePage() { const ids = visible.map((item) => item.id); setSelected((current) => allVisibleSelected ? current.filter((id) => !ids.includes(id)) : [...new Set([...current, ...ids])]); }
  return <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900/70">
    <div className="border-b border-slate-200 p-4 dark:border-white/10"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-slate-500">{filtered.length} records</p></div><label className="flex h-10 min-w-0 flex-1 items-center gap-2 rounded-lg border border-slate-300 px-3 lg:ml-5 dark:border-white/15"><FiSearch className="text-slate-400" /><input className="w-full bg-transparent text-sm outline-none" onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${title.toLowerCase()}...`} value={search} /></label>{filterKey ? <select className="h-10 rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-white/15 dark:bg-slate-900" onChange={(event) => setFilter(event.target.value)} value={filter}><option value="all">All {filterKey}</option>{options.map((option) => <option key={option}>{option}</option>)}</select> : null}<button className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-slate-300 px-3 text-sm font-bold dark:border-white/15" onClick={() => toast('CSV export is a placeholder.')} type="button"><FiDownload />Export CSV</button></div>{selected.length ? <div className="mt-3 flex flex-wrap items-center gap-3 rounded-lg bg-cyan-50 p-3 text-sm dark:bg-cyan-300/10"><strong>{selected.length} selected</strong><button className="rounded-md bg-cyan-600 px-3 py-1.5 font-bold text-white" onClick={() => toast.success(`Bulk action queued for ${selected.length} records.`)} type="button">Apply bulk action</button><button className="font-bold text-slate-600 dark:text-slate-300" onClick={() => setSelected([])} type="button">Clear</button></div> : null}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-white/5"><tr><th className="w-12 px-4 py-3"><input aria-label="Select visible rows" checked={allVisibleSelected} onChange={togglePage} type="checkbox" /></th>{columns.map((column) => <th className="px-4 py-3" key={column.key}><button className="inline-flex items-center gap-1 font-bold uppercase" onClick={() => toggleSort(column.key)} type="button">{column.label}<FiChevronDown className={sortKey === column.key && !ascending ? 'rotate-180' : ''} /></button></th>)}</tr></thead><tbody className="divide-y divide-slate-200 dark:divide-white/10">{visible.map((item) => <tr className="transition hover:bg-slate-50 dark:hover:bg-white/5" key={item.id}><td className="px-4 py-4"><input aria-label={`Select ${item.id}`} checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} type="checkbox" /></td>{columns.map((column) => <td className="px-4 py-4" key={column.key}>{column.key === filterKey || column.key === 'status' ? <Status value={String(item[column.key])} /> : <span className={column.key === columns[0]?.key ? 'font-bold' : 'text-slate-600 dark:text-slate-300'}>{String(item[column.key])}</span>}</td>)}</tr>)}</tbody></table></div>
    {visible.length === 0 ? <p className="p-8 text-center text-slate-500">No matching records.</p> : null}<div className="flex items-center justify-between border-t border-slate-200 px-4 py-3 text-sm dark:border-white/10"><span className="text-slate-500">Page {page} of {pages}</span><div className="flex gap-2"><button className="rounded-md border px-3 py-1.5 disabled:opacity-40 dark:border-white/15" disabled={page === 1} onClick={() => setPage((value) => value - 1)} type="button">Previous</button><button className="rounded-md border px-3 py-1.5 disabled:opacity-40 dark:border-white/15" disabled={page === pages} onClick={() => setPage((value) => value + 1)} type="button">Next</button></div></div>
  </section>;
}
function Status({ value }: { value: string }) { const positive = ['Active', 'Verified', 'Interview', 'Shortlisted', 'Ready'].includes(value); const warning = ['Pending', 'Review', 'Processing'].includes(value); const tone = positive ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-300/10 dark:text-emerald-200' : warning ? 'bg-amber-50 text-amber-700 dark:bg-amber-300/10 dark:text-amber-200' : 'bg-rose-50 text-rose-700 dark:bg-rose-300/10 dark:text-rose-200'; return <span className={`rounded-md px-2 py-1 text-xs font-bold ${tone}`}>{value}</span>; }

