import { motion } from 'framer-motion';
import { useEffect, useState } from 'react';
import toast from 'react-hot-toast';
import { FiBookmark, FiMapPin, FiShare2, FiStar, FiZap } from 'react-icons/fi';
import { Link, useNavigate, useParams } from 'react-router-dom';

import { DiscoveryJobCard } from '@/components/JobDiscovery/DiscoveryJobCard';
import { DiscoverySkeleton } from '@/components/JobDiscovery/DiscoverySkeleton';
import { jobService } from '@/services/jobService';
import type { JobPosting } from '@/types/jobs';

export function JobDetailsPage() {
  const { jobId = '' } = useParams();
  const navigate = useNavigate();
  const [job, setJob] = useState<JobPosting>();
  const [similar, setSimilar] = useState<JobPosting[]>([]);
  useEffect(() => { void Promise.all([jobService.getJob(jobId), jobService.getSimilarJobs(jobId)]).then(([detail, related]) => { setJob(detail); setSimilar(related.jobs); }).catch(() => toast.error('Unable to load job details.')); }, [jobId]);
  if (!job) return <div className="mt-6"><DiscoverySkeleton /></div>;
  async function save() { if (!job) return; if (!job.is_saved) await jobService.saveJob(job.id); setJob({ ...job, is_saved: !job.is_saved }); toast.success(job.is_saved ? 'Removed from saved jobs.' : 'Job saved.'); }
  function apply() { if (job) navigate(`/candidate/dashboard/jobs/${job.id}/apply`); }
  async function share() { await navigator.clipboard?.writeText(window.location.href); toast.success('Job link copied.'); }
  return <motion.div animate={{ opacity: 1 }} className="mt-6 space-y-5" initial={{ opacity: 0 }}>
    <header className="rounded-lg border border-slate-200 bg-white p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/70"><div className="flex flex-col gap-5 md:flex-row md:items-start md:justify-between"><div className="flex gap-4"><div className="grid size-14 shrink-0 place-items-center rounded-lg bg-cyan-50 text-xl font-black text-cyan-700 dark:bg-cyan-300/10">{job.company.slice(0, 2).toUpperCase()}</div><div><div className="flex flex-wrap gap-2"><span className="rounded bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700 dark:bg-emerald-300/10 dark:text-emerald-200">{job.job_status}</span><span className="rounded bg-cyan-50 px-2 py-1 text-xs font-bold text-cyan-700 dark:bg-cyan-300/10 dark:text-cyan-200">{job.work_mode}</span></div><h1 className="mt-2 text-3xl font-bold text-slate-950 dark:text-white">{job.title}</h1><p className="mt-1 font-semibold text-slate-600 dark:text-slate-300">{job.company} · {job.location}</p></div></div><div className="flex flex-wrap gap-2"><button aria-label="Save job" className="grid size-11 place-items-center rounded-md border border-slate-200 dark:border-white/10" onClick={save} type="button"><FiBookmark className={job.is_saved ? 'fill-cyan-600 text-cyan-600' : ''}/></button><button aria-label="Share job" className="grid size-11 place-items-center rounded-md border border-slate-200 dark:border-white/10" onClick={share} type="button"><FiShare2 /></button><button className="flex h-11 items-center gap-2 rounded-md bg-cyan-600 px-5 font-bold text-white disabled:opacity-60" disabled={job.is_applied} onClick={apply} type="button"><FiZap />{job.is_applied ? 'Applied' : 'Apply now'}</button></div></div><div className="mt-6 grid gap-3 border-t border-slate-100 pt-5 sm:grid-cols-2 lg:grid-cols-4 dark:border-white/10">{[['Salary', job.salary_range], ['Experience', job.experience_level], ['Employment', job.employment_type], ['Posted', job.posted_at]].map(([label, value]) => <div key={label}><p className="text-xs font-bold uppercase text-slate-500">{label}</p><p className="mt-1 font-bold text-slate-950 dark:text-white">{value}</p></div>)}</div></header>
    <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_310px]"><main className="space-y-5">{[['Job description', [job.description]], ['Responsibilities', job.responsibilities], ['Requirements', job.requirements], ['Benefits', job.benefits]].map(([title, items]) => <section className="border-b border-slate-200 pb-5 dark:border-white/10" key={title as string}><h2 className="text-xl font-bold text-slate-950 dark:text-white">{title as string}</h2><ul className="mt-3 space-y-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{(items as string[]).map((item) => <li className="flex gap-2" key={item}><span className="mt-2 size-1.5 shrink-0 rounded-full bg-cyan-500"/>{item}</li>)}</ul></section>)}<section><h2 className="text-xl font-bold text-slate-950 dark:text-white">Required skills</h2><div className="mt-3 flex flex-wrap gap-2">{job.skills.map((skill) => <span className="rounded-md bg-cyan-50 px-3 py-1.5 text-sm font-bold text-cyan-800 dark:bg-cyan-300/10 dark:text-cyan-200" key={skill}>{skill}</span>)}</div></section></main><aside className="space-y-4 rounded-lg border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900/70"><h2 className="font-bold text-slate-950 dark:text-white">About {job.company}</h2><p className="text-sm leading-6 text-slate-600 dark:text-slate-300">{job.company_overview}</p><p className="flex items-center gap-2 text-sm font-bold"><FiStar className="fill-amber-400 text-amber-400" />{job.company_rating} company rating</p><p className="flex items-start gap-2 text-sm text-slate-600 dark:text-slate-300"><FiMapPin className="mt-1 shrink-0 text-cyan-600" />{job.office_location}</p><div className="grid grid-cols-3 gap-2">{job.company_photos.map((photo, index) => <div className={`grid aspect-square place-items-center rounded-md p-2 text-center text-[10px] font-bold ${index % 2 ? 'bg-amber-100 text-amber-900' : 'bg-cyan-100 text-cyan-900'}`} key={photo}>{photo}</div>)}</div></aside></div>
    <section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-bold text-slate-950 dark:text-white">Similar jobs</h2><Link className="text-sm font-bold text-cyan-700 dark:text-cyan-300" to={`/candidate/dashboard/jobs/${job.id}/similar`}>View all</Link></div><div className="grid gap-4 xl:grid-cols-2">{similar.slice(0, 2).map((item, index) => <DiscoveryJobCard index={index} job={item} key={item.id} onApply={() => toast.success('Quick application placeholder submitted.')} onSave={() => toast.success('Job saved.')} onShare={() => toast.success('Job link copied.')} query="" view="grid" />)}</div></section>
  </motion.div>;
}
