import { motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { FiCalendar, FiCheck, FiEye, FiSearch, FiX } from 'react-icons/fi';

import { CompanyPageHeader } from '@/components/CompanyDashboard/CompanyPageHeader';
import { CompanySkeleton } from '@/components/CompanyDashboard/CompanySkeleton';
import { companyService } from '@/services/companyService';
import type { CompanyApplicant } from '@/types/company';

export function ApplicantsPage() {
  const [items, setItems] = useState<CompanyApplicant[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [status, setStatus] = useState('All'); const [selected, setSelected] = useState<CompanyApplicant | null>(null);
  useEffect(() => { void companyService.getApplicants().then((response) => { setItems(response.applicants); setLoading(false); }); }, []);
  const visible = useMemo(() => items.filter((item) => (status === 'All' || item.status === status) && `${item.name} ${item.role} ${item.skills.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [items, search, status]);
  if (loading) return <CompanySkeleton />;
  function update(id: string, next: string) { setItems((current) => current.map((item) => item.id === id ? { ...item, status: next } : item)); toast.success(`Applicant moved to ${next}.`); }
  return <div className="mt-6 space-y-6"><CompanyPageHeader description="Review candidates, manage hiring stages, and coordinate recruiter follow-up." title="Applicants" />
    <section className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-slate-900/70"><div className="grid gap-3 md:grid-cols-[1fr_auto]"><label className="flex h-11 items-center gap-3 rounded-lg border border-slate-300 px-3 dark:border-white/15"><FiSearch /><input className="w-full bg-transparent text-sm outline-none" onChange={(event) => setSearch(event.target.value)} placeholder="Search applicants or skills..." /></label><select className="h-11 rounded-lg border border-slate-300 bg-white px-3 dark:border-white/15 dark:bg-slate-900" onChange={(event) => setStatus(event.target.value)}><option>All</option><option>New</option><option>Review</option><option>Shortlisted</option><option>Interview</option><option>Rejected</option></select></div></section>
    <div className="grid gap-4">{visible.map((applicant) => <motion.article className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900/70" key={applicant.id} layout whileHover={{ y: -2 }}><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-lg bg-gradient-to-br from-cyan-500 to-emerald-500 font-bold text-white">{applicant.name.split(' ').map((part) => part[0]).join('')}</span><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-lg font-bold">{applicant.name}</h2><span className="rounded-md bg-cyan-50 px-2 py-1 text-xs font-bold text-cyan-700 dark:bg-cyan-300/10 dark:text-cyan-200">{applicant.match_score}% match</span><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-white/10">{applicant.status}</span></div><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{applicant.role} / {applicant.experience} / {applicant.location}</p><div className="mt-3 flex flex-wrap gap-2">{applicant.skills.map((skill) => <span className="rounded-md border border-slate-200 px-2 py-1 text-xs dark:border-white/10" key={skill}>{skill}</span>)}</div><p className="mt-3 text-xs text-slate-500">Applied {applicant.applied_at}</p></div></div><div className="flex flex-wrap gap-2 lg:justify-end"><button className="inline-flex items-center gap-2 rounded-md border border-slate-300 px-3 py-2 text-sm font-bold dark:border-white/15" onClick={() => setSelected(applicant)} type="button"><FiEye />Resume</button><button aria-label="Shortlist applicant" className="grid size-10 place-items-center rounded-md bg-emerald-50 text-emerald-700 dark:bg-emerald-300/10 dark:text-emerald-200" onClick={() => update(applicant.id, 'Shortlisted')} type="button"><FiCheck /></button><button aria-label="Reject applicant" className="grid size-10 place-items-center rounded-md bg-rose-50 text-rose-700 dark:bg-rose-300/10 dark:text-rose-200" onClick={() => update(applicant.id, 'Rejected')} type="button"><FiX /></button><button aria-label="Schedule interview" className="grid size-10 place-items-center rounded-md bg-cyan-600 text-white" onClick={() => toast('Interview scheduling is a placeholder.')} type="button"><FiCalendar /></button></div></div><textarea aria-label={`Notes for ${applicant.name}`} className="mt-4 min-h-16 w-full rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm outline-none dark:border-white/10 dark:bg-white/5" placeholder="Add recruiter notes..." /></motion.article>)}</div>
    {selected ? <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="w-full max-w-2xl rounded-lg bg-white p-6 dark:bg-slate-900"><div className="flex justify-between"><div><p className="text-sm font-bold text-cyan-700">Resume preview placeholder</p><h2 className="mt-2 text-2xl font-bold">{selected.name}</h2></div><button aria-label="Close preview" onClick={() => setSelected(null)}><FiX /></button></div><div className="mt-6 grid min-h-72 place-items-center rounded-lg border border-dashed border-slate-300 bg-slate-50 text-center dark:border-white/15 dark:bg-white/5"><div><FiEye className="mx-auto size-8 text-cyan-600" /><p className="mt-3 font-bold">Resume document preview</p><p className="mt-1 text-sm text-slate-500">Document rendering will be connected in a later phase.</p></div></div></div></div> : null}
  </div>;
}
