import { motion } from 'framer-motion';
import { useState } from 'react';
import toast from 'react-hot-toast';
import { FiBell, FiCalendar, FiCheckCircle, FiHelpCircle, FiLock, FiSend, FiSettings, FiUser, FiVideo } from 'react-icons/fi';

import { CompanyPageHeader } from '@/components/CompanyDashboard/CompanyPageHeader';

const interviews = [
  { name: 'Priya Kapoor', role: 'Backend Engineer', date: 'Aug 5, 2026 / 10:30 AM', status: 'Upcoming' },
  { name: 'Maya Chen', role: 'Senior Frontend Engineer', date: 'Aug 6, 2026 / 2:00 PM', status: 'Upcoming' },
  { name: 'Noah Williams', role: 'Product Designer', date: 'Aug 1, 2026 / 11:00 AM', status: 'Completed' },
  { name: 'Ethan Brooks', role: 'Data Engineer', date: 'Jul 30, 2026 / 4:00 PM', status: 'Cancelled' },
];
export function CompanyInterviewsPage() {
  const [filter, setFilter] = useState('Upcoming'); return <Workspace title="Interviews" description="Coordinate upcoming, completed, and cancelled candidate conversations."><div className="flex flex-wrap gap-2">{['Upcoming', 'Completed', 'Cancelled'].map((item) => <button className={`rounded-md px-4 py-2 text-sm font-bold ${filter === item ? 'bg-cyan-600 text-white' : 'border border-slate-300 dark:border-white/15'}`} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><div className="mt-5 grid gap-4 lg:grid-cols-2">{interviews.filter((item) => item.status === filter).map((item) => <Card key={item.name}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-lg bg-cyan-50 text-cyan-700 dark:bg-cyan-300/10"><FiVideo /></span><span className="rounded-md bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-white/10">{item.status}</span></div><h2 className="mt-4 text-lg font-bold">{item.name}</h2><p className="text-sm text-slate-500">{item.role}</p><p className="mt-4 flex items-center gap-2 text-sm"><FiCalendar />{item.date}</p></Card>)}</div><div className="mt-6 rounded-lg border border-dashed border-slate-300 p-8 text-center dark:border-white/15"><FiCalendar className="mx-auto size-8 text-cyan-600" /><p className="mt-3 font-bold">Interview calendar placeholder</p></div></Workspace>;
}

const conversations = [{ name: 'Maya Chen', text: 'Thank you for the update!', unread: 2 }, { name: 'Priya Kapoor', text: 'Tuesday works well for me.', unread: 0 }, { name: 'Noah Williams', text: 'Portfolio link attached.', unread: 1 }];
export function CompanyMessagesPage() { const [active, setActive] = useState(conversations[0]); return <Workspace title="Messages" description="Review recruiter conversations and candidate coordination."><div className="grid min-h-[34rem] overflow-hidden rounded-lg border border-slate-200 lg:grid-cols-[20rem_1fr] dark:border-white/10"><aside className="border-b border-slate-200 lg:border-b-0 lg:border-r dark:border-white/10">{conversations.map((conversation) => <button className={`flex w-full items-center gap-3 border-b border-slate-200 p-4 text-left dark:border-white/10 ${active.name === conversation.name ? 'bg-cyan-50 dark:bg-cyan-300/10' : ''}`} onClick={() => setActive(conversation)} key={conversation.name}><span className="grid size-10 place-items-center rounded-lg bg-slate-900 font-bold text-white dark:bg-white dark:text-slate-900">{conversation.name[0]}</span><span className="min-w-0 flex-1"><strong className="block truncate">{conversation.name}</strong><span className="block truncate text-xs text-slate-500">{conversation.text}</span></span>{conversation.unread ? <span className="grid size-5 place-items-center rounded-full bg-cyan-600 text-xs text-white">{conversation.unread}</span> : null}</button>)}</aside><section className="flex min-h-96 flex-col"><div className="border-b border-slate-200 p-4 font-bold dark:border-white/10">{active.name}</div><div className="flex-1 space-y-4 p-5"><div className="max-w-sm rounded-lg bg-slate-100 p-3 text-sm dark:bg-white/10">I wanted to confirm the next step in the interview process.</div><div className="ml-auto max-w-sm rounded-lg bg-cyan-600 p-3 text-sm text-white">Thanks for checking in. We will share the schedule shortly.</div></div><div className="flex gap-2 border-t border-slate-200 p-4 dark:border-white/10"><input className="h-11 flex-1 rounded-lg border border-slate-300 bg-transparent px-3 outline-none dark:border-white/15" placeholder="Write a message..." /><button aria-label="Send message" className="grid size-11 place-items-center rounded-lg bg-cyan-600 text-white" onClick={() => toast('Messaging is a placeholder.')}><FiSend /></button></div></section></div></Workspace>; }

const notices = [{ icon: FiUser, title: '18 new applications', text: 'Senior Frontend Engineer received new candidates.', time: '10 min ago' }, { icon: FiCalendar, title: 'Interview reminder', text: 'Priya Kapoor is scheduled tomorrow at 10:30 AM.', time: '1 hour ago' }, { icon: FiBell, title: 'Job performance update', text: 'Product Designer views increased by 24%.', time: 'Yesterday' }];
export function CompanyNotificationsPage() { return <Workspace title="Notifications" description="Stay current on applications, interviews, and recruiter activity."><div className="space-y-3">{notices.map((notice) => { const Icon = notice.icon; return <Card key={notice.title}><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-cyan-50 text-cyan-700 dark:bg-cyan-300/10"><Icon /></span><div><h2 className="font-bold">{notice.title}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{notice.text}</p><p className="mt-2 text-xs text-slate-500">{notice.time}</p></div></div></Card>; })}</div></Workspace>; }

export function CompanySubscriptionPage() { return <Workspace title="Subscription" description="Review your current plan, billing history, and premium workspace status."><Card><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold uppercase text-emerald-600">Current Plan</p><h2 className="mt-2 text-3xl font-bold">Business Pro</h2><p className="mt-2 text-sm text-slate-500">Renews September 3, 2026 / $249 per month</p></div><button className="rounded-lg bg-cyan-600 px-5 py-3 font-bold text-white" onClick={() => toast('Plan upgrades are a placeholder.')}>Upgrade Plan</button></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{['Unlimited job posts', 'Advanced analytics', 'Priority support'].map((item) => <div className="flex items-center gap-2 text-sm font-semibold" key={item}><FiCheckCircle className="text-emerald-600" />{item}</div>)}</div></Card><Card><h2 className="text-lg font-bold">Billing History</h2><div className="mt-4 divide-y divide-slate-200 dark:divide-white/10">{['Aug 3, 2026', 'Jul 3, 2026', 'Jun 3, 2026'].map((date) => <div className="grid grid-cols-[1fr_auto_auto] gap-4 py-4 text-sm" key={date}><span>{date}</span><span className="font-bold">$249.00</span><span className="text-emerald-600">Paid</span></div>)}</div></Card></Workspace>; }

export function CompanySettingsPage() { return <Workspace title="Settings" description="Configure company preferences, alerts, and account security."><div className="grid gap-6 lg:grid-cols-2"><SettingsCard icon={<FiSettings />} title="Company Preferences" items={['Show salary ranges publicly', 'Allow remote applicants', 'Enable candidate match scoring']} /><SettingsCard icon={<FiBell />} title="Notification Settings" items={['New application alerts', 'Interview reminders', 'Weekly hiring summary']} /></div><Card><div className="flex items-center gap-3"><FiLock className="text-cyan-600" /><h2 className="text-lg font-bold">Security Settings</h2></div><div className="mt-5 grid gap-4 md:grid-cols-3"><input className="h-11 rounded-lg border border-slate-300 bg-transparent px-3 dark:border-white/15" placeholder="Current password" type="password" /><input className="h-11 rounded-lg border border-slate-300 bg-transparent px-3 dark:border-white/15" placeholder="New password" type="password" /><button className="rounded-lg bg-cyan-600 px-4 font-bold text-white" onClick={() => toast('Password update is a placeholder.')}>Change Password</button></div></Card></Workspace>; }

export function CompanyHelpPage() { return <Workspace title="Help Center" description="Find answers and contact support for your company workspace."><div className="grid gap-4 md:grid-cols-3">{['Posting and managing jobs', 'Reviewing applicants', 'Billing and subscriptions'].map((title) => <Card key={title}><FiHelpCircle className="size-6 text-cyan-600" /><h2 className="mt-4 font-bold">{title}</h2><p className="mt-2 text-sm text-slate-500">Browse practical guidance for this company workflow.</p></Card>)}</div><Card><h2 className="text-lg font-bold">Need more help?</h2><p className="mt-2 text-sm text-slate-500">Contact enterprise support for account and hiring workflow assistance.</p><button className="mt-4 rounded-lg bg-cyan-600 px-4 py-2 font-bold text-white" onClick={() => toast('Support contact is a placeholder.')}>Contact Support</button></Card></Workspace>; }

function Workspace({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="mt-6 space-y-6"><CompanyPageHeader description={description} title={title} />{children}</div>; }
function Card({ children }: { children: React.ReactNode }) { return <motion.section animate={{ opacity: 1, y: 0 }} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900/70" initial={{ opacity: 0, y: 12 }}>{children}</motion.section>; }
function SettingsCard({ icon, title, items }: { icon: React.ReactNode; title: string; items: string[] }) { return <Card><div className="flex items-center gap-3 text-lg font-bold">{icon}{title}</div><div className="mt-5 space-y-4">{items.map((item) => <label className="flex items-center justify-between gap-4 text-sm font-semibold" key={item}>{item}<input className="size-4 accent-cyan-600" defaultChecked type="checkbox" /></label>)}</div></Card>; }
