import { motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { FiCopy, FiEdit2, FiMoreVertical, FiSearch, FiTrash2, FiXCircle } from 'react-icons/fi';

import { CompanyPageHeader } from '@/components/CompanyDashboard/CompanyPageHeader';
import { CompanySkeleton } from '@/components/CompanyDashboard/CompanySkeleton';
import { companyService } from '@/services/companyService';
import type { CompanyJob } from '@/types/company';

const pageSize = 3;
export function ManageJobsPage() {
  const [jobs, setJobs] = useState<CompanyJob[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [status, setStatus] = useState('all'); const [sort, setSort] = useState('newest'); const [page, setPage] = useState(1); const [menu, setMenu] = useState<string | null>(null);
  useEffect(() => { void companyService.getJobs().then((response) => { setJobs(response.jobs); setLoading(false); }); }, []);
  const filtered = useMemo(() => jobs.filter((job) => (status === 'all' || job.status === status) && `${job.title} ${job.department}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'applications' ? (b.applications ?? 0) - (a.applications ?? 0) : sort === 'title' ? a.title.localeCompare(b.title) : (b.created_at ?? '').localeCompare(a.created_at ?? '')), [jobs, search, sort, status]);
  useEffect(() => setPage(1), [search, sort, status]);
  if (loading) return <CompanySkeleton />;
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize); const pages = Math.max(1, Math.ceil(filtered.length / pageSize));
  async function remove(job: CompanyJob) { if (!job.id) return; await companyService.deleteJob(job.id); setJobs((items) => items.filter((item) => item.id !== job.id)); toast.success('Job removed from the dummy list.'); }
  async function close(job: CompanyJob) { if (!job.id) return; const updated = { ...job, status: 'closed' }; await companyService.updateJob(job.id, updated); setJobs((items) => items.map((item) => item.id === job.id ? updated : item)); toast.success('Job closed.'); }
  function duplicate(job: CompanyJob) { setJobs((items) => [{ ...job, id: `${job.id}-copy`, title: `${job.title} (Copy)`, status: 'draft', applications: 0, views: 0 }, ...items]); toast.success('Job duplicated as draft.'); }
  return <div className="mt-6 space-y-6"><CompanyPageHeader description="Search, review, and maintain all published, draft, and closed positions." title="Manage Jobs" />
    <section className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm dark:border-white/10 dark:bg-slate-900/70"><div className="grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="flex h-11 items-center gap-3 rounded-lg border border-slate-300 px-3 dark:border-white/15"><FiSearch className="text-slate-400" /><input className="w-full bg-transparent text-sm outline-none" onChange={(event) => setSearch(event.target.value)} placeholder="Search jobs..." value={search} /></label><select className="h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-white/15 dark:bg-slate-900" onChange={(event) => setStatus(event.target.value)} value={status}><option value="all">All statuses</option><option value="active">Active</option><option value="draft">Draft</option><option value="closed">Closed</option></select><select className="h-11 rounded-lg border border-slate-300 bg-white px-3 text-sm dark:border-white/15 dark:bg-slate-900" onChange={(event) => setSort(event.target.value)} value={sort}><option value="newest">Newest</option><option value="applications">Most applications</option><option value="title">Job title</option></select></div></section>
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900/70"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500 dark:bg-white/5"><tr><th className="px-5 py-4">Job</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Applications</th><th className="px-5 py-4">Views</th><th className="px-5 py-4">Created</th><th className="px-5 py-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-200 dark:divide-white/10">{visible.map((job) => <motion.tr animate={{ opacity: 1 }} initial={{ opacity: 0 }} key={job.id}><td className="px-5 py-4"><p className="font-bold">{job.title}</p><p className="mt-1 text-xs text-slate-500">{job.department} / {job.work_mode}</p></td><td className="px-5 py-4"><Status value={job.status} /></td><td className="px-5 py-4 font-semibold">{job.applications}</td><td className="px-5 py-4">{job.views}</td><td className="px-5 py-4 text-slate-500">{job.created_at}</td><td className="relative px-5 py-4 text-right"><button aria-label={`Actions for ${job.title}`} className="grid size-9 place-items-center rounded-md hover:bg-slate-100 dark:hover:bg-white/10" onClick={() => setMenu(menu === job.id ? null : job.id ?? null)} type="button"><FiMoreVertical /></button>{menu === job.id ? <div className="absolute right-5 z-10 w-44 rounded-lg border border-slate-200 bg-white p-2 text-left shadow-xl dark:border-white/10 dark:bg-slate-900"><Action icon={<FiEdit2 />} label="Edit" onClick={() => toast('Job editing uses the placeholder update API.')} /><Action icon={<FiCopy />} label="Duplicate" onClick={() => duplicate(job)} /><Action icon={<FiXCircle />} label="Close" onClick={() => void close(job)} /><Action danger icon={<FiTrash2 />} label="Delete" onClick={() => void remove(job)} /></div> : null}</td></motion.tr>)}</tbody></table></div>{visible.length === 0 ? <p className="p-8 text-center text-slate-500">No jobs match the current filters.</p> : null}<div className="flex items-center justify-between border-t border-slate-200 px-5 py-4 text-sm dark:border-white/10"><span className="text-slate-500">Page {page} of {pages}</span><div className="flex gap-2"><button className="rounded-md border px-3 py-1.5 disabled:opacity-40 dark:border-white/15" disabled={page === 1} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="rounded-md border px-3 py-1.5 disabled:opacity-40 dark:border-white/15" disabled={page === pages} onClick={() => setPage((value) => value + 1)}>Next</button></div></div></section>
  </div>;
}
function Status({ value }: { value: string }) { const tone = value === 'active' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-300/10 dark:text-emerald-200' : value === 'draft' ? 'bg-amber-50 text-amber-700 dark:bg-amber-300/10 dark:text-amber-200' : 'bg-slate-100 text-slate-600 dark:bg-white/10 dark:text-slate-300'; return <span className={`rounded-md px-2 py-1 text-xs font-bold capitalize ${tone}`}>{value}</span>; }
function Action({ icon, label, onClick, danger = false }: { icon: React.ReactNode; label: string; onClick: () => void; danger?: boolean }) { return <button className={`flex w-full items-center gap-2 rounded-md px-3 py-2 text-sm font-semibold hover:bg-slate-100 dark:hover:bg-white/10 ${danger ? 'text-rose-600' : ''}`} onClick={onClick} type="button">{icon}{label}</button>; }
