import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import { FiClock, FiFileText, FiMessageSquare, FiUsers, FiVideo } from 'react-icons/fi';

import { CompanyPageHeader } from '@/components/CompanyDashboard/CompanyPageHeader';

const interviews = [{ name: 'Maya Chen', role: 'Senior Frontend Engineer', time: 'Aug 6, 10:00 AM', type: 'Technical' }, { name: 'Priya Kapoor', role: 'Platform Engineer', time: 'Aug 7, 2:30 PM', type: 'HR' }, { name: 'Noah Williams', role: 'Product Designer', time: 'Aug 8, 11:00 AM', type: 'Final' }];
export function RecruiterInterviewsPage() { return <Workspace title="Interview Management" description="Coordinate candidate interviews and recruiter follow-up."><div className="grid gap-4 lg:grid-cols-3">{interviews.map((item) => <Card key={item.name}><FiVideo className="size-6 text-cyan-600"/><h2 className="mt-4 font-bold">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.role}</p><p className="mt-4 flex items-center gap-2 text-sm font-semibold"><FiClock/>{item.time}</p><span className="mt-3 inline-flex rounded bg-cyan-50 px-2 py-1 text-xs font-bold text-cyan-700 dark:bg-cyan-300/10">{item.type} Interview</span><button className="mt-4 h-9 w-full rounded-md border text-sm font-bold dark:border-white/10" onClick={() => toast('Interview management is a placeholder.')}>Manage interview</button></Card>)}</div></Workspace>; }
export function HiringPipelinePage() { return <Workspace title="Hiring Pipeline" description="Review hiring throughput and stage-level conversion placeholders."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Active candidates','48'],['Interviews','12'],['Offers','5'],['Hired','3']].map(([label,value]) => <Card key={label}><p className="text-sm font-semibold text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>)}</div><Card><h2 className="font-bold">Pipeline health</h2><div className="mt-5 grid gap-3">{[['Screening',72],['Interviews',48],['Offers',24],['Hired',14]].map(([label,value]) => <div key={label}><div className="flex justify-between text-sm font-semibold"><span>{label}</span><span>{value}%</span></div><div className="mt-1 h-2 rounded-full bg-slate-100 dark:bg-white/10"><div className="h-full rounded-full bg-cyan-600" style={{ width: `${value}%` }}/></div></div>)}</div></Card></Workspace>; }
export function RecruiterNotesPage() { return <Workspace title="Recruiter Notes" description="Review internal notes across active candidates."><div className="grid gap-4">{['Strong system-design discussion and clear tradeoff thinking.','Follow up on leadership examples before final review.','Portfolio demonstrates excellent product judgment.'].map((note,index) => <Card key={note}><div className="flex gap-3"><FiFileText className="mt-1 shrink-0 text-cyan-600"/><div><p className="text-sm leading-6">{note}</p><p className="mt-2 text-xs font-semibold text-slate-500">Candidate {index + 1} · Jordan Lee</p></div></div></Card>)}</div></Workspace>; }
export function TeamCollaborationPage() { return <Workspace title="Team Collaboration" description="Coordinate hiring feedback and recruiter ownership."><Card><FiUsers className="size-8 text-cyan-600"/><h2 className="mt-4 text-lg font-bold">Shared hiring workspace</h2><p className="mt-2 text-sm text-slate-500">Mentions, assignments, approvals, and shared scorecards will be connected later.</p><button className="mt-4 rounded-md bg-cyan-600 px-4 py-2 font-bold text-white" onClick={() => toast('Team collaboration is a placeholder.')}><FiMessageSquare className="inline"/> Invite teammate</button></Card></Workspace>; }
export function HiringCalendarPage() { return <Workspace title="Hiring Calendar" description="Plan interviews, reviews, and offer milestones."><Card><div className="grid grid-cols-7 gap-2">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day) => <div className="text-center text-xs font-bold text-slate-500" key={day}>{day}</div>)}{Array.from({length:35},(_,index) => <button className={`aspect-square rounded-md border text-sm font-semibold dark:border-white/10 ${[5,11,18,24].includes(index) ? 'bg-cyan-600 text-white' : ''}`} key={index} onClick={() => toast('Calendar scheduling is a placeholder.')}>{index < 3 ? '' : index - 2}</button>)}</div></Card></Workspace>; }
function Workspace({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="mt-6 space-y-5"><CompanyPageHeader description={description} title={title}/>{children}</div>; }
function Card({ children }: { children: React.ReactNode }) { return <motion.section animate={{ opacity: 1, y: 0 }} className="rounded-lg border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900/70" initial={{ opacity: 0, y: 10 }}>{children}</motion.section>; }
