import gsap from 'gsap';
import { motion } from 'framer-motion';
import { useEffect, useMemo, useRef, useState } from 'react';
import toast from 'react-hot-toast';
import { FiBookmark, FiSearch, FiStar } from 'react-icons/fi';
import { Link } from 'react-router-dom';

import { CompanyPageHeader } from '@/components/CompanyDashboard/CompanyPageHeader';
import { CompanySkeleton } from '@/components/CompanyDashboard/CompanySkeleton';
import { recruiterService } from '@/services/recruiterService';
import { PIPELINE_STAGES, type PipelineStage, type RecruiterCandidate } from '@/types/recruiter';

export function RecruiterPipelinePage() {
  const boardRef = useRef<HTMLDivElement>(null); const [candidates, setCandidates] = useState<RecruiterCandidate[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [dragging, setDragging] = useState<string>();
  useEffect(() => { void recruiterService.getCandidates().then((response) => setCandidates(response.candidates)).catch(() => toast.error('Unable to load pipeline.')).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!loading) gsap.fromTo('.pipeline-column', { opacity: 0, x: 18 }, { opacity: 1, x: 0, stagger: 0.04, duration: 0.35 }); }, [loading]);
  const visible = useMemo(() => candidates.filter((candidate) => `${candidate.name} ${candidate.skills.join(' ')} ${candidate.experience} ${candidate.status} ${candidate.rating} ${candidate.job_title}`.toLowerCase().includes(search.toLowerCase())), [candidates, search]);
  async function move(candidateId: string, status: PipelineStage) { const candidate = candidates.find((item) => item.id === candidateId); if (!candidate || candidate.status === status) return; setCandidates((current) => current.map((item) => item.id === candidateId ? { ...item, status } : item)); try { await recruiterService.updateStatus(candidateId, status); toast.success(`${candidate.name} moved to ${status}.`); } catch { setCandidates((current) => current.map((item) => item.id === candidateId ? candidate : item)); toast.error('Unable to update pipeline.'); } }
  if (loading) return <CompanySkeleton />;
  return <div className="mt-6 space-y-5"><CompanyPageHeader description="Move candidates through every stage of the company hiring process." title="Applicant Pipeline" /><label className="flex h-11 max-w-xl items-center gap-3 rounded-lg border border-slate-200 bg-white px-3 dark:border-white/10 dark:bg-slate-900"><FiSearch /><input className="w-full bg-transparent text-sm outline-none" onChange={(event) => setSearch(event.target.value)} placeholder="Search name, skill, experience, status, rating, or job" value={search}/></label><div className="overflow-x-auto pb-4" ref={boardRef}><div className="grid min-w-max grid-flow-col auto-cols-[280px] gap-4">{PIPELINE_STAGES.map((stage) => { const stageCandidates = visible.filter((candidate) => candidate.status === stage); return <section className="pipeline-column min-h-[30rem] rounded-lg border border-slate-200 bg-slate-100/70 p-3 dark:border-white/10 dark:bg-white/5" key={stage} onDragOver={(event) => event.preventDefault()} onDrop={() => { if (dragging) void move(dragging, stage); setDragging(undefined); }}><div className="flex items-center justify-between px-1"><h2 className="text-sm font-bold">{stage}</h2><span className="grid size-6 place-items-center rounded-full bg-white text-xs font-bold dark:bg-slate-800">{stageCandidates.length}</span></div><div className="mt-3 space-y-3">{stageCandidates.map((candidate) => <motion.article className="cursor-grab rounded-lg border border-slate-200 bg-white p-4 shadow-sm active:cursor-grabbing dark:border-white/10 dark:bg-slate-900" draggable key={candidate.id} layout onDragStart={() => setDragging(candidate.id)} whileHover={{ y: -2 }}><div className="flex items-start justify-between gap-2"><span className="grid size-9 place-items-center rounded-md bg-cyan-600 text-xs font-bold text-white">{candidate.name.split(' ').map((part) => part[0]).join('')}</span>{candidate.bookmarked && <FiBookmark className="fill-cyan-600 text-cyan-600"/>}</div><Link className="mt-3 block font-bold hover:text-cyan-700" to={`/company/dashboard/candidates/${candidate.id}`}>{candidate.name}</Link><p className="mt-1 line-clamp-2 text-xs text-slate-500">{candidate.job_title}</p><div className="mt-3 flex items-center justify-between text-xs"><span>{candidate.experience}</span><span className="flex items-center gap-1 font-bold text-amber-600"><FiStar className="fill-current"/>{candidate.rating}</span></div><div className="mt-3 flex flex-wrap gap-1">{candidate.tags.map((tag) => <span className="rounded bg-slate-100 px-2 py-1 text-[10px] font-bold dark:bg-white/10" key={tag}>{tag}</span>)}</div></motion.article>)}</div></section>; })}</div></div></div>;
}
