import { motion } from 'framer-motion';
import { useEffect, useMemo, useState } from 'react';
import { FiBookmark, FiSearch, FiStar } from 'react-icons/fi';
import { Link } from 'react-router-dom';

import { CompanyPageHeader } from '@/components/CompanyDashboard/CompanyPageHeader';
import { CompanySkeleton } from '@/components/CompanyDashboard/CompanySkeleton';
import { recruiterService } from '@/services/recruiterService';
import { PIPELINE_STAGES, type RecruiterCandidate } from '@/types/recruiter';

export function RecruiterCandidatesPage() {
  const [items, setItems] = useState<RecruiterCandidate[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [stage, setStage] = useState('All'); const [rating, setRating] = useState('All');
  useEffect(() => { void recruiterService.getCandidates().then((response) => setItems(response.candidates)).finally(() => setLoading(false)); }, []);
  const visible = useMemo(() => items.filter((item) => (stage === 'All' || item.status === stage) && (rating === 'All' || item.rating >= Number(rating)) && `${item.name} ${item.skills.join(' ')} ${item.experience} ${item.job_title}`.toLowerCase().includes(search.toLowerCase())), [items, rating, search, stage]);
  if (loading) return <CompanySkeleton />;
  return <div className="mt-6 space-y-5"><CompanyPageHeader description="Search and review every candidate in the active hiring portfolio." title="Candidate Profiles"/><div className="grid gap-3 rounded-lg border border-slate-200 bg-white p-4 md:grid-cols-[1fr_200px_150px] dark:border-white/10 dark:bg-slate-900/70"><label className="flex h-11 items-center gap-3 rounded-md border px-3 dark:border-white/10"><FiSearch/><input className="w-full bg-transparent text-sm outline-none" onChange={(event) => setSearch(event.target.value)} placeholder="Search name, skills, experience, or job"/></label><select className="rounded-md border bg-white px-3 text-sm font-bold dark:border-white/10 dark:bg-slate-900" onChange={(event) => setStage(event.target.value)}><option>All</option>{PIPELINE_STAGES.map((item) => <option key={item}>{item}</option>)}</select><select className="rounded-md border bg-white px-3 text-sm font-bold dark:border-white/10 dark:bg-slate-900" onChange={(event) => setRating(event.target.value)}><option>All</option>{[5,4,3,2,1].map((item) => <option key={item} value={item}>{item}+ stars</option>)}</select></div><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((candidate, index) => <motion.article animate={{ opacity: 1, y: 0 }} className="rounded-lg border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900/70" initial={{ opacity: 0, y: 10 }} key={candidate.id} transition={{ delay: index * .03 }}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-lg bg-cyan-600 font-bold text-white">{candidate.name.split(' ').map((part) => part[0]).join('')}</span><FiBookmark className={candidate.bookmarked ? 'fill-cyan-600 text-cyan-600' : 'text-slate-400'}/></div><Link className="mt-4 block text-lg font-bold hover:text-cyan-700" to={`/company/dashboard/candidates/${candidate.id}`}>{candidate.name}</Link><p className="text-sm text-slate-500">{candidate.headline}</p><div className="mt-3 flex items-center justify-between"><span className="rounded bg-cyan-50 px-2 py-1 text-xs font-bold text-cyan-700 dark:bg-cyan-300/10">{candidate.status}</span><span className="flex items-center gap-1 font-bold text-amber-600"><FiStar className="fill-current"/>{candidate.rating}</span></div><div className="mt-4 flex flex-wrap gap-1.5">{candidate.skills.slice(0,4).map((skill) => <span className="rounded border px-2 py-1 text-xs dark:border-white/10" key={skill}>{skill}</span>)}</div><p className="mt-4 text-xs text-slate-500">{candidate.experience} · Applied to {candidate.job_title}</p></motion.article>)}</section>{!visible.length && <div className="rounded-lg border border-dashed py-16 text-center dark:border-white/15"><h2 className="font-bold">No candidates found</h2></div>}</div>;
}
