import { motion } from 'framer-motion';
import toast from 'react-hot-toast';
import { FiBell, FiCpu, FiLock, FiMail, FiMessageCircle, FiSave, FiSettings, FiShield, FiUser } from 'react-icons/fi';
import { AdminPageHeader } from '@/components/AdminDashboard/AdminPageHeader';
import { AdminTable } from '@/components/AdminDashboard/AdminTable';
import type { AdminRecord } from '@/types/admin';

const activity: AdminRecord[] = [
  { id: 'act-1', actor: 'Morgan Admin', action: 'Verified company account', target: 'Northstar Labs', timestamp: 'Aug 3, 10:42 AM', status: 'Success' },
  { id: 'act-2', actor: 'System', action: 'Flagged unusual login', target: 'usr-8842', timestamp: 'Aug 3, 9:18 AM', status: 'Review' },
  { id: 'act-3', actor: 'Alex Admin', action: 'Closed support ticket', target: 'TKT-1028', timestamp: 'Aug 2, 5:34 PM', status: 'Success' },
  { id: 'act-4', actor: 'System', action: 'Completed daily backup', target: 'Primary database', timestamp: 'Aug 2, 3:00 AM', status: 'Success' },
];
const audit: AdminRecord[] = [
  { id: 'aud-1', event: 'ROLE_PERMISSION_CHANGED', admin: 'Morgan Admin', resource: 'support_manager', ip: '10.0.14.22', timestamp: 'Aug 3, 11:05 AM', status: 'Success' },
  { id: 'aud-2', event: 'COMPANY_SUSPENDED', admin: 'Alex Admin', resource: 'Atlas Retail', ip: '10.0.14.31', timestamp: 'Aug 3, 8:42 AM', status: 'Success' },
  { id: 'aud-3', event: 'LOGIN_FAILED', admin: 'Unknown', resource: 'admin@example.com', ip: '198.51.100.8', timestamp: 'Aug 2, 11:19 PM', status: 'Review' },
];
const tickets: AdminRecord[] = [
  { id: 'TKT-1032', subject: 'Unable to publish a job', requester: 'Northstar Labs', priority: 'High', status: 'Open', updated: '12 min ago' },
  { id: 'TKT-1031', subject: 'Candidate profile data request', requester: 'Ava Stone', priority: 'Medium', status: 'Pending', updated: '1 hour ago' },
  { id: 'TKT-1029', subject: 'Billing invoice correction', requester: 'SignalWorks', priority: 'Low', status: 'Resolved', updated: 'Yesterday' },
  { id: 'TKT-1028', subject: 'Account verification', requester: 'Vertex Cloud', priority: 'Medium', status: 'Resolved', updated: 'Yesterday' },
  { id: 'TKT-1027', subject: 'Login assistance', requester: 'Maya Chen', priority: 'High', status: 'Open', updated: 'Aug 1' },
];

export function AdminActivityPage() { return <TablePage title="Activity Logs" description="Monitor operational events and recent administrative activity." data={activity} columns={[{ key: 'actor', label: 'Actor' }, { key: 'action', label: 'Action' }, { key: 'target', label: 'Target' }, { key: 'timestamp', label: 'Timestamp' }, { key: 'status', label: 'Status' }]} />; }
export function AdminAuditPage() { return <TablePage title="Audit Logs" description="Review immutable security-sensitive administrative events." data={audit} columns={[{ key: 'event', label: 'Event' }, { key: 'admin', label: 'Admin' }, { key: 'resource', label: 'Resource' }, { key: 'ip', label: 'IP Address' }, { key: 'status', label: 'Status' }]} />; }
export function AdminSupportPage() { return <TablePage title="Support Tickets" description="Triage user and company requests across the support queue." data={tickets} columns={[{ key: 'subject', label: 'Subject' }, { key: 'requester', label: 'Requester' }, { key: 'priority', label: 'Priority' }, { key: 'status', label: 'Status' }, { key: 'updated', label: 'Updated' }]} />; }

export function AdminNotificationsPage() { const items = [{ title: 'Infrastructure alert resolved', text: 'API latency returned to normal operating thresholds.', time: '8 minutes ago' }, { title: 'Company verification queue', text: '14 employer accounts are awaiting review.', time: '45 minutes ago' }, { title: 'Policy report threshold', text: 'Three job posts require moderator attention.', time: '2 hours ago' }]; return <Workspace title="Notifications" description="Review platform, security, moderation, and operational alerts."><div className="space-y-3">{items.map((item) => <Card key={item.title}><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-rose-50 text-rose-600 dark:bg-rose-300/10"><FiBell /></span><div><h2 className="font-bold">{item.title}</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{item.text}</p><p className="mt-2 text-xs text-slate-500">{item.time}</p></div></div></Card>)}</div></Workspace>; }

export function AdminFeedbackPage() { const feedback = [{ name: 'Ava Stone', type: 'Candidate', score: 5, text: 'The resume analysis report is clear and actionable.' }, { name: 'Northstar Labs', type: 'Company', score: 4, text: 'Applicant filtering is fast; more export formats would help.' }, { name: 'Maya Chen', type: 'Candidate', score: 4, text: 'Job matching feels relevant and easy to navigate.' }]; return <Workspace title="Feedback Management" description="Review product sentiment and prioritize platform improvements."><div className="grid gap-4 lg:grid-cols-3">{feedback.map((item) => <Card key={item.name}><div className="flex items-center justify-between"><FiMessageCircle className="size-6 text-rose-600" /><span className="font-bold text-amber-500">{item.score}/5</span></div><p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">{item.text}</p><p className="mt-4 font-bold">{item.name}</p><p className="text-xs text-slate-500">{item.type}</p></Card>)}</div></Workspace>; }

export function AdminAISettingsPage() { return <Workspace title="AI Settings" description="Prepare governance controls for future AI provider integrations."><Card><div className="flex items-center gap-3"><FiCpu className="size-6 text-rose-600" /><h2 className="text-lg font-bold">AI Provider Configuration</h2></div><div className="mt-5 grid gap-5 md:grid-cols-2"><Field label="Provider"><select><option>Not configured</option><option>Placeholder provider</option></select></Field><Field label="Default model"><input disabled placeholder="Connect a provider first" /></Field><Field label="Monthly usage limit"><input type="number" defaultValue="100000" /></Field><Field label="Moderation policy"><select><option>Strict</option><option>Balanced</option></select></Field></div><button className="mt-5 rounded-lg bg-rose-600 px-4 py-2.5 font-bold text-white" onClick={() => toast('AI provider configuration is a placeholder.')} type="button">Save Placeholder Settings</button></Card></Workspace>; }

export function AdminSettingsPage() { return <Workspace title="System Settings" description="Manage your admin profile, security, email, theme, and platform defaults."><div className="grid gap-6 xl:grid-cols-2"><SettingsSection icon={<FiUser />} title="Admin Profile"><Field label="Display name"><input defaultValue="Morgan Admin" /></Field><Field label="Email"><input defaultValue="admin@aihirepro.example" type="email" /></Field><SaveButton text="Save Profile" /></SettingsSection><SettingsSection icon={<FiLock />} title="Password"><Field label="Current password"><input type="password" /></Field><Field label="New password"><input type="password" /></Field><SaveButton text="Change Password" /></SettingsSection><SettingsSection icon={<FiMail />} title="Email Settings"><Field label="From name"><input defaultValue="AIHire Pro" /></Field><Field label="Support email"><input defaultValue="support@aihirepro.example" /></Field><label className="mt-4 flex items-center justify-between text-sm font-semibold">Send weekly system report<input defaultChecked type="checkbox" /></label><SaveButton text="Save Email Settings" /></SettingsSection><SettingsSection icon={<FiSettings />} title="System Configuration"><Field label="Default locale"><select><option>English (US)</option></select></Field><Field label="Maintenance mode"><select><option>Disabled</option><option>Enabled</option></select></Field><label className="mt-4 flex items-center justify-between text-sm font-semibold">Dark theme preference<input defaultChecked type="checkbox" /></label><SaveButton text="Save Configuration" /></SettingsSection></div><Card><div className="flex items-center gap-3"><FiShield className="text-emerald-600" /><h2 className="font-bold">Security posture</h2></div><p className="mt-3 text-sm text-slate-500">Role enforcement, JWT validation, audit logging, and protected admin routing are active.</p></Card></Workspace>; }

function TablePage({ title, description, data, columns }: { title: string; description: string; data: AdminRecord[]; columns: Array<{ key: string; label: string }> }) { return <div className="mt-6 space-y-6"><AdminPageHeader description={description} title={title} /><AdminTable columns={columns} data={data} filterKey="status" title={title} /></div>; }
function Workspace({ title, description, children }: { title: string; description: string; children: React.ReactNode }) { return <div className="mt-6 space-y-6"><AdminPageHeader description={description} title={title} />{children}</div>; }
function Card({ children }: { children: React.ReactNode }) { return <motion.section animate={{ opacity: 1, y: 0 }} className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900/70" initial={{ opacity: 0, y: 12 }}>{children}</motion.section>; }
function Field({ label, children }: { label: string; children: React.ReactElement }) { return <label className="block text-sm font-bold text-slate-700 dark:text-slate-200">{label}<div className="mt-2 [&>*]:h-11 [&>*]:w-full [&>*]:rounded-lg [&>*]:border [&>*]:border-slate-300 [&>*]:bg-transparent [&>*]:px-3 dark:[&>*]:border-white/15">{children}</div></label>; }
function SettingsSection({ icon, title, children }: { icon: React.ReactNode; title: string; children: React.ReactNode }) { return <Card><div className="flex items-center gap-3 text-lg font-bold text-rose-600">{icon}<span className="text-slate-950 dark:text-white">{title}</span></div><div className="mt-5 space-y-4">{children}</div></Card>; }
function SaveButton({ text }: { text: string }) { return <button className="inline-flex items-center gap-2 rounded-lg bg-rose-600 px-4 py-2.5 font-bold text-white" onClick={() => toast.success(`${text} placeholder completed.`)} type="button"><FiSave />{text}</button>; }
