import { useEffect, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { AdminPageHeader } from '@/components/AdminDashboard/AdminPageHeader';
import { AdminSkeleton } from '@/components/AdminDashboard/AdminSkeleton';
import { adminService } from '@/services/adminService';
import type { AdminDashboard } from '@/types/admin';

export function AdminAnalyticsPage() { const [data, setData] = useState<AdminDashboard | null>(null); useEffect(() => { void adminService.getDashboard().then(setData); }, []); if (!data) return <AdminSkeleton />; return <div className="mt-6 space-y-6"><AdminPageHeader description="Explore platform growth, marketplace demand, and user engagement signals." title="Platform Analytics" /><div className="grid gap-6 xl:grid-cols-2"><Chart title="User and job growth"><ResponsiveContainer height="100%" width="100%"><LineChart data={data.user_growth.map((item, index) => ({ ...item, jobs: data.job_growth[index]?.jobs }))}><CartesianGrid stroke="rgba(148,163,184,.25)" strokeDasharray="3 3" /><XAxis dataKey="label" /><YAxis /><Tooltip /><Legend /><Line dataKey="users" stroke="#e11d48" strokeWidth={3} type="monotone" /><Line dataKey="jobs" stroke="#0891b2" strokeWidth={3} type="monotone" /></LineChart></ResponsiveContainer></Chart><Chart title="Application trend"><ResponsiveContainer height="100%" width="100%"><AreaChart data={data.application_trend}><CartesianGrid stroke="rgba(148,163,184,.25)" strokeDasharray="3 3" /><XAxis dataKey="label" /><Tooltip /><Area dataKey="applications" fill="#10b98144" stroke="#10b981" strokeWidth={3} type="monotone" /></AreaChart></ResponsiveContainer></Chart><Chart title="Most applied jobs"><ResponsiveContainer height="100%" width="100%"><BarChart data={data.most_applied_jobs} layout="vertical"><XAxis type="number" /><YAxis dataKey="name" type="category" width={110} tick={{ fontSize: 11 }} /><Tooltip /><Bar dataKey="applications" fill="#8b5cf6" radius={[0, 4, 4, 0]} /></BarChart></ResponsiveContainer></Chart><Chart title="Active users"><ResponsiveContainer height="100%" width="100%"><AreaChart data={data.active_users}><XAxis dataKey="label" /><Tooltip /><Area dataKey="users" fill="#f59e0b44" stroke="#f59e0b" strokeWidth={3} type="monotone" /></AreaChart></ResponsiveContainer></Chart></div></div>; }
function Chart({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-slate-900/70"><h2 className="text-lg font-bold">{title}</h2><div className="mt-5 h-80">{children}</div></section>; }

